//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdManage
    {
        public int ID { get; set; }
        public string Position { get; set; }
        public int PositionId { get; set; }
        public byte[] Image { get; set; }
        public bool AllowImage { get; set; }
        public bool AllowText { get; set; }
        public Nullable<int> ImageLimit { get; set; }
        public Nullable<int> TextLimit { get; set; }
        public Nullable<double> ImageWidth { get; set; }
        public Nullable<double> ImageHeight { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public bool Enabled { get; set; }
        public int Creator { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public int Modify { get; set; }
        public string AllowImageType { get; set; }
        public bool SaleOff { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public int Days { get; set; }
    }
}
