//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdOrder()
        {
            this.AdImage = new HashSet<AdImage>();
        }
    
        public int ID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Position { get; set; }
        public decimal bought { get; set; }
        public bool AllowImage { get; set; }
        public bool AllowText { get; set; }
        public Nullable<int> ImageLimit { get; set; }
        public Nullable<int> TextLimit { get; set; }
        public Nullable<double> ImageWidth { get; set; }
        public Nullable<double> ImageHeight { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Status { get; set; }
        public string Href { get; set; }
        public int Days { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int AdId { get; set; }
        public int PositionId { get; set; }
        public string Text { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdImage> AdImage { get; set; }
        public virtual AdManage AdManage { get; set; }
    }
}
