//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int ID { get; set; }
        public string MerchantOrderNo { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int Amount { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public System.DateTime Created { get; set; }
        public string Remark { get; set; }
        public System.DateTime Modified { get; set; }
        public int Modify { get; set; }
        public string PayVendor { get; set; }
        public Nullable<double> ShareBonus { get; set; }
        public Nullable<double> BoughtBonus { get; set; }
        public Nullable<double> SystemBonus { get; set; }
        public string TradeNo { get; set; }
        public string TradeStatus { get; set; }
        public string PaymentType { get; set; }
        public string ProductType { get; set; }
        public int Creator { get; set; }
    
        public virtual PayGo PayGo { get; set; }
    }
}
