//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPrice
    {
        public int ID { get; set; }
        public int RoomId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public System.DateTime Date { get; set; }
        public bool SaleOff { get; set; }
        public int Amount { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
