//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomImage = new HashSet<RoomImage>();
            this.RoomPrice = new HashSet<RoomPrice>();
        }
    
        public int ID { get; set; }
        public int HotelId { get; set; }
        public string Name { get; set; }
        public string Notice { get; set; }
        public int MaxPerson { get; set; }
        public int BedAmount { get; set; }
        public int BedType { get; set; }
        public string Feature { get; set; }
        public decimal FixedPrice { get; set; }
        public decimal HolidayPrice { get; set; }
        public decimal DayPrice { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Created { get; set; }
        public int Creator { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> Modify { get; set; }
        public bool Enabled { get; set; }
        public Nullable<bool> HasBreakfast { get; set; }
        public int RoomType { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImage> RoomImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomPrice> RoomPrice { get; set; }
    }
}
