//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysManage
    {
        public int ID { get; set; }
        public string FieldCode { get; set; }
        public string FieldDescription { get; set; }
        public string Value { get; set; }
        public string Unit { get; set; }
        public bool Enabled { get; set; }
        public int Editor { get; set; }
        public System.DateTime Edited { get; set; }
        public string FieldName { get; set; }
    }
}
