//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPOrder
    {
        public int ID { get; set; }
        public int Vip { get; set; }
        public decimal Pay { get; set; }
        public string PayMethod { get; set; }
        public string OrderStatus { get; set; }
        public string PayType { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
    
        public virtual VIPs VIPs { get; set; }
    }
}
