//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anything.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPs
    {
        public int ID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Days { get; set; }
        public int HotelId { get; set; }
    
        public virtual VIPOrder VIPOrder { get; set; }
        public virtual VIPs VIPs1 { get; set; }
        public virtual VIPs VIPs2 { get; set; }
    }
}
